on:
  push:
    branches:
      - main
    
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    permissions:    
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4        

      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create image
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=DefaultContainer
