on:
  push:
    branches:
    - main

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    permissions:    
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3        

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create image
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=DefaultContainer
